apiVersion: v1
kind: Namespace
metadata:
  name: wireguard
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: wg-overlay-service
  namespace: wireguard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-operator
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: wg-overlay
subjects:
- kind: ServiceAccount
  name: wg-overlay-service
  namespace: wireguard
roleRef:
  kind: ClusterRole
  name: node-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: wg-overlay
  name: wireguard-network-service
  namespace: wireguard
spec:
  selector:
    matchLabels:
      k8s-app: wg-overlay
  template:
    metadata:
      labels:
        k8s-app: wg-overlay
    spec:
      hostNetwork: true
      hostPID: true
      hostIPC: true
      terminationGracePeriodSeconds: 0
      serviceAccountName: wg-overlay-service
      volumes:
      - name: wg-vol
        hostPath:
          path: /etc/wireguard
          type: DirectoryOrCreate
      containers:
      - name: wireguard-network-service
        env:
        - name: OVERLAY_CIDR
          value: 100.64.0.0/16
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        image: tylloyd/wg-network-service:v20220223-a
        imagePullPolicy: Always
        command: ["/wireguard-network-service"]
        volumeMounts:
        - mountPath: /etc/wireguard
          name: wg-vol
      - name: wns-sync
        image: busybox:latest
        securityContext:
          privileged: true
        command:
          - nsenter
          - --target
          - "1"
          - --mount
          - --uts
          - --ipc
          - --net
          - --pid
          - --
          - bash
          - -exc
          - |
            while :
            do
              echo "checking wireguard config ... "
              if [ -f "/etc/wireguard/update" ]; then
                echo "updating wg-quick@wg0.service"
                systemctl restart wg-quick@wg0.service
                rm /etc/wireguard/update
              else
                echo "re-sync in 5 sec"
              fi
              sleep 5
            done
      initContainers:
      - name: wireguard-init
        image: busybox:latest
        securityContext:
          privileged: true
        command:
          - nsenter
          - --target
          - "1"
          - --mount
          - --uts
          - --ipc
          - --net
          - --pid
          - --
          - bash
          - -ce
          - |
            missingWg=$(dpkg -s wireguard | grep "install ok")
            if [ -z "$missingWg" ]; then
              echo "Installing wireguard..."
              sudo apt update
              sudo apt install -y wireguard
            fi
            PRIVATE_KEY_FILE=/etc/wireguard/privatekey
            PUBLIC_KEY_FILE=/etc/wireguard/publickey

            if [ -f "$PRIVATE_KEY_FILE" ]; then
              echo "private key already created"
            else
              sudo wg genkey > /etc/wireguard/privatekey
            fi
            
            if [ -f "$PUBLIC_KEY_FILE" ]; then
              echo "public key already created:"
              cat /etc/wireguard/publickey
            else
              cat /etc/wireguard/privatekey | sudo wg pubkey > /etc/wireguard/publickey
            fi
            if [ -f "/etc/wireguard/wg0.conf" ]; then
              echo "found existing wg0.conf"
            else
              touch /etc/wireguard/wg0.conf
            fi
            systemctl enable wg-quick@wg0.service
            systemctl start wg-quick@wg0.service
